package net.flamesparks4143.item;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.flamesparks4143.item.custom.*;
import net.flamesparks4143.item.custom.other_papers.creeper_charge.*;
import net.flamesparks4143.item.custom.other_papers.flower_charge.*;
import net.flamesparks4143.item.custom.other_papers.globe.*;
import net.flamesparks4143.item.custom.other_papers.skull_charge.*;
import net.flamesparks4143.item.custom.other_papers.snout.*;
import net.flamesparks4143.item.custom.other_papers.thing.*;
import net.flamesparks4143.item.custom.paper.brown.*;
import net.flamesparks4143.item.custom.paper.cyan.*;
import net.flamesparks4143.item.custom.paper.gray.*;
import net.flamesparks4143.item.custom.paper.green.*;
import net.flamesparks4143.item.custom.paper.light_blue.*;
import net.flamesparks4143.item.custom.paper.light_gray.*;
import net.flamesparks4143.item.custom.paper.lime.*;
import net.flamesparks4143.item.custom.paper.magenta.*;
import net.flamesparks4143.item.custom.paper.orange.*;
import net.flamesparks4143.item.custom.paper.pink.*;
import net.flamesparks4143.item.custom.paper.purple.*;
import net.flamesparks4143.item.custom.paper.red.*;
import net.flamesparks4143.item.custom.paper.white.*;
import net.flamesparks4143.item.custom.paper.yellow.*;

import net.flamesparks4143.victorian_madess.FlamesVictorianMadness;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModItems {
    public static final Item STEEL_INGOT = registerItem("steel_ingot", new Item(new FabricItemSettings()));
    public static final Item VICTORIAN_BANNER_PATTERN = registerItem("victorian_banner_pattern", new Item(new FabricItemSettings()));
    public static final Item STEEL_NUGGET = registerItem("steel_nugget", new Item(new FabricItemSettings()));
    public static final Item RAW_PORCELAIN = registerItem("raw_porcelain", new Item(new FabricItemSettings()));
    public static final Item PORCELAIN_BRICK = registerItem("porcelain_brick", new Item(new FabricItemSettings()));
    public static final Item CHISEL = registerItem("chisel_tool", new ChiselTool(new Item.Settings().maxDamage(64)));
    public static final Item GLASS_CUTTER = registerItem("glass_cutter", new GlassCutterTool(new Item.Settings().maxDamage(64)));

    public static final Item CHAIN_LINKS_BANNER_PATTERN = registerItem("chain_links_banner_pattern", new Item(new FabricItemSettings()));

    public static final Item BLACK_CHAIN_LINK_PAPER = registerItem("black_chain_link_paper", new BlackChainLinkPaperItem(new Item.Settings()));
    public static final Item BLACK_CHECKERED_PAPER = registerItem("black_checkered_paper", new BlackCheckeredPaperItem(new Item.Settings()));
    public static final Item BLACK_CIRCULAR_PAPER = registerItem("black_circular_paper", new BlackCircularPaperItem(new Item.Settings()));
    public static final Item BLACK_CROSSED_PAPER = registerItem("black_crossed_paper", new BlackCrossedPaperItem(new Item.Settings()));
    public static final Item BLACK_DIAMOND_PAPER = registerItem("black_diamond_paper", new BlackDiamondPaperItem(new Item.Settings()));
    public static final Item BLACK_GRASS_PAPER = registerItem("black_grass_paper", new BlackGrassPaperItem(new Item.Settings()));
    public static final Item BLACK_INTERLINKED_PAPER = registerItem("black_interlinked_paper", new BlackInterlinkedPaperItem(new Item.Settings()));
    public static final Item BLACK_LAYERED_PAPER = registerItem("black_layered_paper", new BlackLayeredPaperItem(new Item.Settings()));
    public static final Item BLACK_LILY_FLOWER_PAPER = registerItem("black_lily_flower_paper", new BlackLilyFlowerPaperItem(new Item.Settings()));
    public static final Item BLACK_OCULAR_PAPER = registerItem("black_ocular_paper", new BlackOcularPaperItem(new Item.Settings()));
    public static final Item BLACK_OVAL_PAPER = registerItem("black_oval_paper", new BlackOvalPaperItem(new Item.Settings()));
    public static final Item BLACK_PYRIFORM_PAPER = registerItem("black_pyriform_paper", new BlackPyriformPaperItem(new Item.Settings()));
    public static final Item BLACK_SCALES_PAPER = registerItem("black_scales_paper", new BlackScalesPaperItem(new Item.Settings()));
    public static final Item BLACK_TWISTED_PAPER = registerItem("black_twisted_paper", new BlackTwistedPaperItem(new Item.Settings()));
    public static final Item BLACK_TWO_STARRED_PAPER = registerItem("black_two_starred_paper", new BlackTwoStarredPaperItem(new Item.Settings()));
    public static final Item BLACK_ZIPPER_PAPER = registerItem("black_zipper_paper", new BlackZipperPaperItem(new Item.Settings()));
    public static final Item BLUE_CHAIN_LINK_PAPER = registerItem("blue_chain_link_paper", new BlueChainLinkPaperItem(new Item.Settings()));
    public static final Item BLUE_CHECKERED_PAPER = registerItem("blue_checkered_paper", new BlueCheckeredPaperItem(new Item.Settings()));
    public static final Item BLUE_CIRCULAR_PAPER = registerItem("blue_circular_paper", new BlueCircularPaperItem(new Item.Settings()));
    public static final Item BLUE_CROSSED_PAPER = registerItem("blue_crossed_paper", new BlueCrossedPaperItem(new Item.Settings()));
    public static final Item BLUE_DIAMOND_PAPER = registerItem("blue_diamond_paper", new BlueDiamondPaperItem(new Item.Settings()));
    public static final Item BLUE_GRASS_PAPER = registerItem("blue_grass_paper", new BlueGrassPaperItem(new Item.Settings()));
    public static final Item BLUE_INTERLINKED_PAPER = registerItem("blue_interlinked_paper", new BlueInterlinkedPaperItem(new Item.Settings()));
    public static final Item BLUE_LAYERED_PAPER = registerItem("blue_layered_paper", new BlueLayeredPaperItem(new Item.Settings()));
    public static final Item BLUE_LILY_FLOWER_PAPER = registerItem("blue_lily_flower_paper", new BlueLilyFlowerPaperItem(new Item.Settings()));
    public static final Item BLUE_OCULAR_PAPER = registerItem("blue_ocular_paper", new BlueOcularPaperItem(new Item.Settings()));
    public static final Item BLUE_OVAL_PAPER = registerItem("blue_oval_paper", new BlueOvalPaperItem(new Item.Settings()));
    public static final Item BLUE_PYRIFORM_PAPER = registerItem("blue_pyriform_paper", new BluePyriformPaperItem(new Item.Settings()));
    public static final Item BLUE_SCALES_PAPER = registerItem("blue_scales_paper", new BlueScalesPaperItem(new Item.Settings()));
    public static final Item BLUE_TWISTED_PAPER = registerItem("blue_twisted_paper", new BlueTwistedPaperItem(new Item.Settings()));
    public static final Item BLUE_TWO_STARRED_PAPER = registerItem("blue_two_starred_paper", new BlueTwoStarredPaperItem(new Item.Settings()));
    public static final Item BLUE_ZIPPER_PAPER = registerItem("blue_zipper_paper", new BlueZipperPaperItem(new Item.Settings()));
    public static final Item BROWN_CHAIN_LINK_PAPER = registerItem("brown_chain_link_paper", new BrownChainLinkPaperItem(new Item.Settings()));
    public static final Item BROWN_CHECKERED_PAPER = registerItem("brown_checkered_paper", new BrownCheckeredPaperItem(new Item.Settings()));
    public static final Item BROWN_CIRCULAR_PAPER = registerItem("brown_circular_paper", new BrownCircularPaperItem(new Item.Settings()));
    public static final Item BROWN_CROSSED_PAPER = registerItem("brown_crossed_paper", new BrownCrossedPaperItem(new Item.Settings()));
    public static final Item BROWN_DIAMOND_PAPER = registerItem("brown_diamond_paper", new BrownDiamondPaperItem(new Item.Settings()));
    public static final Item BROWN_GRASS_PAPER = registerItem("brown_grass_paper", new BrownGrassPaperItem(new Item.Settings()));
    public static final Item BROWN_INTERLINKED_PAPER = registerItem("brown_interlinked_paper", new BrownInterlinkedPaperItem(new Item.Settings()));
    public static final Item BROWN_LAYERED_PAPER = registerItem("brown_layered_paper", new BrownLayeredPaperItem(new Item.Settings()));
    public static final Item BROWN_LILY_FLOWER_PAPER = registerItem("brown_lily_flower_paper", new BrownLilyFlowerPaperItem(new Item.Settings()));
    public static final Item BROWN_OCULAR_PAPER = registerItem("brown_ocular_paper", new BrownOcularPaperItem(new Item.Settings()));
    public static final Item BROWN_OVAL_PAPER = registerItem("brown_oval_paper", new BrownOvalPaperItem(new Item.Settings()));
    public static final Item BROWN_PYRIFORM_PAPER = registerItem("brown_pyriform_paper", new BrownPyriformPaperItem(new Item.Settings()));
    public static final Item BROWN_SCALES_PAPER = registerItem("brown_scales_paper", new BrownScalesPaperItem(new Item.Settings()));
    public static final Item BROWN_TWISTED_PAPER = registerItem("brown_twisted_paper", new BrownTwistedPaperItem(new Item.Settings()));
    public static final Item BROWN_TWO_STARRED_PAPER = registerItem("brown_two_starred_paper", new BrownTwoStarredPaperItem(new Item.Settings()));
    public static final Item BROWN_ZIPPER_PAPER = registerItem("brown_zipper_paper", new BrownZipperPaperItem(new Item.Settings()));
    public static final Item CYAN_CHAIN_LINK_PAPER = registerItem("cyan_chain_link_paper", new CyanChainLinkPaperItem(new Item.Settings()));
    public static final Item CYAN_CHECKERED_PAPER = registerItem("cyan_checkered_paper", new CyanCheckeredPaperItem(new Item.Settings()));
    public static final Item CYAN_CIRCULAR_PAPER = registerItem("cyan_circular_paper", new CyanCircularPaperItem(new Item.Settings()));
    public static final Item CYAN_CROSSED_PAPER = registerItem("cyan_crossed_paper", new CyanCrossedPaperItem(new Item.Settings()));
    public static final Item CYAN_DIAMOND_PAPER = registerItem("cyan_diamond_paper", new CyanDiamondPaperItem(new Item.Settings()));
    public static final Item CYAN_GRASS_PAPER = registerItem("cyan_grass_paper", new CyanGrassPaperItem(new Item.Settings()));
    public static final Item CYAN_INTERLINKED_PAPER = registerItem("cyan_interlinked_paper", new CyanInterlinkedPaperItem(new Item.Settings()));
    public static final Item CYAN_LAYERED_PAPER = registerItem("cyan_layered_paper", new CyanLayeredPaperItem(new Item.Settings()));
    public static final Item CYAN_LILY_FLOWER_PAPER = registerItem("cyan_lily_flower_paper", new CyanLilyFlowerPaperItem(new Item.Settings()));
    public static final Item CYAN_OCULAR_PAPER = registerItem("cyan_ocular_paper", new CyanOcularPaperItem(new Item.Settings()));
    public static final Item CYAN_OVAL_PAPER = registerItem("cyan_oval_paper", new CyanOvalPaperItem(new Item.Settings()));
    public static final Item CYAN_PYRIFORM_PAPER = registerItem("cyan_pyriform_paper", new CyanPyriformPaperItem(new Item.Settings()));
    public static final Item CYAN_SCALES_PAPER = registerItem("cyan_scales_paper", new CyanScalesPaperItem(new Item.Settings()));
    public static final Item CYAN_TWISTED_PAPER = registerItem("cyan_twisted_paper", new CyanTwistedPaperItem(new Item.Settings()));
    public static final Item CYAN_TWO_STARRED_PAPER = registerItem("cyan_two_starred_paper", new CyanTwoStarredPaperItem(new Item.Settings()));
    public static final Item CYAN_ZIPPER_PAPER = registerItem("cyan_zipper_paper", new CyanZipperPaperItem(new Item.Settings()));
    public static final Item GRAY_CHAIN_LINK_PAPER = registerItem("gray_chain_link_paper", new GrayChainLinkPaperItem(new Item.Settings()));
    public static final Item GRAY_CHECKERED_PAPER = registerItem("gray_checkered_paper", new GrayCheckeredPaperItem(new Item.Settings()));
    public static final Item GRAY_CIRCULAR_PAPER = registerItem("gray_circular_paper", new GrayCircularPaperItem(new Item.Settings()));
    public static final Item GRAY_CROSSED_PAPER = registerItem("gray_crossed_paper", new GrayCrossedPaperItem(new Item.Settings()));
    public static final Item GRAY_DIAMOND_PAPER = registerItem("gray_diamond_paper", new GrayDiamondPaperItem(new Item.Settings()));
    public static final Item GRAY_GRASS_PAPER = registerItem("gray_grass_paper", new GrayGrassPaperItem(new Item.Settings()));
    public static final Item GRAY_INTERLINKED_PAPER = registerItem("gray_interlinked_paper", new GrayInterlinkedPaperItem(new Item.Settings()));
    public static final Item GRAY_LAYERED_PAPER = registerItem("gray_layered_paper", new GrayLayeredPaperItem(new Item.Settings()));
    public static final Item GRAY_LILY_FLOWER_PAPER = registerItem("gray_lily_flower_paper", new GrayLilyFlowerPaperItem(new Item.Settings()));
    public static final Item GRAY_OCULAR_PAPER = registerItem("gray_ocular_paper", new GrayOcularPaperItem(new Item.Settings()));
    public static final Item GRAY_OVAL_PAPER = registerItem("gray_oval_paper", new GrayOvalPaperItem(new Item.Settings()));
    public static final Item GRAY_PYRIFORM_PAPER = registerItem("gray_pyriform_paper", new GrayPyriformPaperItem(new Item.Settings()));
    public static final Item GRAY_SCALES_PAPER = registerItem("gray_scales_paper", new GrayScalesPaperItem(new Item.Settings()));
    public static final Item GRAY_TWISTED_PAPER = registerItem("gray_twisted_paper", new GrayTwistedPaperItem(new Item.Settings()));
    public static final Item GRAY_TWO_STARRED_PAPER = registerItem("gray_two_starred_paper", new GrayTwoStarredPaperItem(new Item.Settings()));
    public static final Item GRAY_ZIPPER_PAPER = registerItem("gray_zipper_paper", new GrayZipperPaperItem(new Item.Settings()));
    public static final Item GREEN_CHAIN_LINK_PAPER = registerItem("green_chain_link_paper", new GreenChainLinkPaperItem(new Item.Settings()));
    public static final Item GREEN_CHECKERED_PAPER = registerItem("green_checkered_paper", new GreenCheckeredPaperItem(new Item.Settings()));
    public static final Item GREEN_CIRCULAR_PAPER = registerItem("green_circular_paper", new GreenCircularPaperItem(new Item.Settings()));
    public static final Item GREEN_CROSSED_PAPER = registerItem("green_crossed_paper", new GreenCrossedPaperItem(new Item.Settings()));
    public static final Item GREEN_DIAMOND_PAPER = registerItem("green_diamond_paper", new GreenDiamondPaperItem(new Item.Settings()));
    public static final Item GREEN_GRASS_PAPER = registerItem("green_grass_paper", new GreenGrassPaperItem(new Item.Settings()));
    public static final Item GREEN_INTERLINKED_PAPER = registerItem("green_interlinked_paper", new GreenInterlinkedPaperItem(new Item.Settings()));
    public static final Item GREEN_LAYERED_PAPER = registerItem("green_layered_paper", new GreenLayeredPaperItem(new Item.Settings()));
    public static final Item GREEN_LILY_FLOWER_PAPER = registerItem("green_lily_flower_paper", new GreenLilyFlowerPaperItem(new Item.Settings()));
    public static final Item GREEN_OCULAR_PAPER = registerItem("green_ocular_paper", new GreenOcularPaperItem(new Item.Settings()));
    public static final Item GREEN_OVAL_PAPER = registerItem("green_oval_paper", new GreenOvalPaperItem(new Item.Settings()));
    public static final Item GREEN_PYRIFORM_PAPER = registerItem("green_pyriform_paper", new GreenPyriformPaperItem(new Item.Settings()));
    public static final Item GREEN_SCALES_PAPER = registerItem("green_scales_paper", new GreenScalesPaperItem(new Item.Settings()));
    public static final Item GREEN_TWISTED_PAPER = registerItem("green_twisted_paper", new GreenTwistedPaperItem(new Item.Settings()));
    public static final Item GREEN_TWO_STARRED_PAPER = registerItem("green_two_starred_paper", new GreenTwoStarredPaperItem(new Item.Settings()));
    public static final Item GREEN_ZIPPER_PAPER = registerItem("green_zipper_paper", new GreenZipperPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_CHAIN_LINK_PAPER = registerItem("light_blue_chain_link_paper", new LightBlueChainLinkPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_CHECKERED_PAPER = registerItem("light_blue_checkered_paper", new LightBlueCheckeredPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_CIRCULAR_PAPER = registerItem("light_blue_circular_paper", new LightBlueCircularPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_CROSSED_PAPER = registerItem("light_blue_crossed_paper", new LightBlueCrossedPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_DIAMOND_PAPER = registerItem("light_blue_diamond_paper", new LightBlueDiamondPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_GRASS_PAPER = registerItem("light_blue_grass_paper", new LightBlueGrassPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_INTERLINKED_PAPER = registerItem("light_blue_interlinked_paper", new LightBlueInterlinkedPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_LAYERED_PAPER = registerItem("light_blue_layered_paper", new LightBlueLayeredPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_LILY_FLOWER_PAPER = registerItem("light_blue_lily_flower_paper", new LightBlueLilyFlowerPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_OCULAR_PAPER = registerItem("light_blue_ocular_paper", new LightBlueOcularPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_OVAL_PAPER = registerItem("light_blue_oval_paper", new LightBlueOvalPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_PYRIFORM_PAPER = registerItem("light_blue_pyriform_paper", new LightBluePyriformPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_SCALES_PAPER = registerItem("light_blue_scales_paper", new LightBlueScalesPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_TWISTED_PAPER = registerItem("light_blue_twisted_paper", new LightBlueTwistedPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_TWO_STARRED_PAPER = registerItem("light_blue_two_starred_paper", new LightBlueTwoStarredPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_ZIPPER_PAPER = registerItem("light_blue_zipper_paper", new LightBlueZipperPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_CHAIN_LINK_PAPER = registerItem("light_gray_chain_link_paper", new LightGrayChainLinkPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_CHECKERED_PAPER = registerItem("light_gray_checkered_paper", new LightGrayCheckeredPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_CIRCULAR_PAPER = registerItem("light_gray_circular_paper", new LightGrayCircularPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_CROSSED_PAPER = registerItem("light_gray_crossed_paper", new LightGrayCrossedPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_DIAMOND_PAPER = registerItem("light_gray_diamond_paper", new LightGrayDiamondPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_GRASS_PAPER = registerItem("light_gray_grass_paper", new LightGrayGrassPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_INTERLINKED_PAPER = registerItem("light_gray_interlinked_paper", new LightGrayInterlinkedPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_LAYERED_PAPER = registerItem("light_gray_layered_paper", new LightGrayLayeredPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_LILY_FLOWER_PAPER = registerItem("light_gray_lily_flower_paper", new LightGrayLilyFlowerPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_OCULAR_PAPER = registerItem("light_gray_ocular_paper", new LightGrayOcularPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_OVAL_PAPER = registerItem("light_gray_oval_paper", new LightGrayOvalPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_PYRIFORM_PAPER = registerItem("light_gray_pyriform_paper", new LightGrayPyriformPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_SCALES_PAPER = registerItem("light_gray_scales_paper", new LightGrayScalesPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_TWISTED_PAPER = registerItem("light_gray_twisted_paper", new LightGrayTwistedPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_TWO_STARRED_PAPER = registerItem("light_gray_two_starred_paper", new LightGrayTwoStarredPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_ZIPPER_PAPER = registerItem("light_gray_zipper_paper", new LightGrayZipperPaperItem(new Item.Settings()));
    public static final Item LIME_CHAIN_LINK_PAPER = registerItem("lime_chain_link_paper", new LimeChainLinkPaperItem(new Item.Settings()));
    public static final Item LIME_CHECKERED_PAPER = registerItem("lime_checkered_paper", new LimeCheckeredPaperItem(new Item.Settings()));
    public static final Item LIME_CIRCULAR_PAPER = registerItem("lime_circular_paper", new LimeCircularPaperItem(new Item.Settings()));
    public static final Item LIME_CROSSED_PAPER = registerItem("lime_crossed_paper", new LimeCrossedPaperItem(new Item.Settings()));
    public static final Item LIME_DIAMOND_PAPER = registerItem("lime_diamond_paper", new LimeDiamondPaperItem(new Item.Settings()));
    public static final Item LIME_GRASS_PAPER = registerItem("lime_grass_paper", new LimeGrassPaperItem(new Item.Settings()));
    public static final Item LIME_INTERLINKED_PAPER = registerItem("lime_interlinked_paper", new LimeInterlinkedPaperItem(new Item.Settings()));
    public static final Item LIME_LAYERED_PAPER = registerItem("lime_layered_paper", new LimeLayeredPaperItem(new Item.Settings()));
    public static final Item LIME_LILY_FLOWER_PAPER = registerItem("lime_lily_flower_paper", new LimeLilyFlowerPaperItem(new Item.Settings()));
    public static final Item LIME_OCULAR_PAPER = registerItem("lime_ocular_paper", new LimeOcularPaperItem(new Item.Settings()));
    public static final Item LIME_OVAL_PAPER = registerItem("lime_oval_paper", new LimeOvalPaperItem(new Item.Settings()));
    public static final Item LIME_PYRIFORM_PAPER = registerItem("lime_pyriform_paper", new LimePyriformPaperItem(new Item.Settings()));
    public static final Item LIME_SCALES_PAPER = registerItem("lime_scales_paper", new LimeScalesPaperItem(new Item.Settings()));
    public static final Item LIME_TWISTED_PAPER = registerItem("lime_twisted_paper", new LimeTwistedPaperItem(new Item.Settings()));
    public static final Item LIME_TWO_STARRED_PAPER = registerItem("lime_two_starred_paper", new LimeTwoStarredPaperItem(new Item.Settings()));
    public static final Item LIME_ZIPPER_PAPER = registerItem("lime_zipper_paper", new LimeZipperPaperItem(new Item.Settings()));
    public static final Item MAGENTA_CHAIN_LINK_PAPER = registerItem("magenta_chain_link_paper", new MagentaChainLinkPaperItem(new Item.Settings()));
    public static final Item MAGENTA_CHECKERED_PAPER = registerItem("magenta_checkered_paper", new MagentaCheckeredPaperItem(new Item.Settings()));
    public static final Item MAGENTA_CIRCULAR_PAPER = registerItem("magenta_circular_paper", new MagentaCircularPaperItem(new Item.Settings()));
    public static final Item MAGENTA_CROSSED_PAPER = registerItem("magenta_crossed_paper", new MagentaCrossedPaperItem(new Item.Settings()));
    public static final Item MAGENTA_DIAMOND_PAPER = registerItem("magenta_diamond_paper", new MagentaDiamondPaperItem(new Item.Settings()));
    public static final Item MAGENTA_GRASS_PAPER = registerItem("magenta_grass_paper", new MagentaGrassPaperItem(new Item.Settings()));
    public static final Item MAGENTA_INTERLINKED_PAPER = registerItem("magenta_interlinked_paper", new MagentaInterlinkedPaperItem(new Item.Settings()));
    public static final Item MAGENTA_LAYERED_PAPER = registerItem("magenta_layered_paper", new MagentaLayeredPaperItem(new Item.Settings()));
    public static final Item MAGENTA_LILY_FLOWER_PAPER = registerItem("magenta_lily_flower_paper", new MagentaLilyFlowerPaperItem(new Item.Settings()));
    public static final Item MAGENTA_OCULAR_PAPER = registerItem("magenta_ocular_paper", new MagentaOcularPaperItem(new Item.Settings()));
    public static final Item MAGENTA_OVAL_PAPER = registerItem("magenta_oval_paper", new MagentaOvalPaperItem(new Item.Settings()));
    public static final Item MAGENTA_PYRIFORM_PAPER = registerItem("magenta_pyriform_paper", new MagentaPyriformPaperItem(new Item.Settings()));
    public static final Item MAGENTA_SCALES_PAPER = registerItem("magenta_scales_paper", new MagentaScalesPaperItem(new Item.Settings()));
    public static final Item MAGENTA_TWISTED_PAPER = registerItem("magenta_twisted_paper", new MagentaTwistedPaperItem(new Item.Settings()));
    public static final Item MAGENTA_TWO_STARRED_PAPER = registerItem("magenta_two_starred_paper", new MagentaTwoStarredPaperItem(new Item.Settings()));
    public static final Item MAGENTA_ZIPPER_PAPER = registerItem("magenta_zipper_paper", new MagentaZipperPaperItem(new Item.Settings()));
    public static final Item ORANGE_CHAIN_LINK_PAPER = registerItem("orange_chain_link_paper", new OrangeChainLinkPaperItem(new Item.Settings()));
    public static final Item ORANGE_CHECKERED_PAPER = registerItem("orange_checkered_paper", new OrangeCheckeredPaperItem(new Item.Settings()));
    public static final Item ORANGE_CIRCULAR_PAPER = registerItem("orange_circular_paper", new OrangeCircularPaperItem(new Item.Settings()));
    public static final Item ORANGE_CROSSED_PAPER = registerItem("orange_crossed_paper", new OrangeCrossedPaperItem(new Item.Settings()));
    public static final Item ORANGE_DIAMOND_PAPER = registerItem("orange_diamond_paper", new OrangeDiamondPaperItem(new Item.Settings()));
    public static final Item ORANGE_GRASS_PAPER = registerItem("orange_grass_paper", new OrangeGrassPaperItem(new Item.Settings()));
    public static final Item ORANGE_INTERLINKED_PAPER = registerItem("orange_interlinked_paper", new OrangeInterlinkedPaperItem(new Item.Settings()));
    public static final Item ORANGE_LAYERED_PAPER = registerItem("orange_layered_paper", new OrangeLayeredPaperItem(new Item.Settings()));
    public static final Item ORANGE_LILY_FLOWER_PAPER = registerItem("orange_lily_flower_paper", new OrangeLilyFlowerPaperItem(new Item.Settings()));
    public static final Item ORANGE_OCULAR_PAPER = registerItem("orange_ocular_paper", new OrangeOcularPaperItem(new Item.Settings()));
    public static final Item ORANGE_OVAL_PAPER = registerItem("orange_oval_paper", new OrangeOvalPaperItem(new Item.Settings()));
    public static final Item ORANGE_PYRIFORM_PAPER = registerItem("orange_pyriform_paper", new OrangePyriformPaperItem(new Item.Settings()));
    public static final Item ORANGE_SCALES_PAPER = registerItem("orange_scales_paper", new OrangeScalesPaperItem(new Item.Settings()));
    public static final Item ORANGE_TWISTED_PAPER = registerItem("orange_twisted_paper", new OrangeTwistedPaperItem(new Item.Settings()));
    public static final Item ORANGE_TWO_STARRED_PAPER = registerItem("orange_two_starred_paper", new OrangeTwoStarredPaperItem(new Item.Settings()));
    public static final Item ORANGE_ZIPPER_PAPER = registerItem("orange_zipper_paper", new OrangeZipperPaperItem(new Item.Settings()));
    public static final Item PINK_CHAIN_LINK_PAPER = registerItem("pink_chain_link_paper", new PinkChainLinkPaperItem(new Item.Settings()));
    public static final Item PINK_CHECKERED_PAPER = registerItem("pink_checkered_paper", new PinkCheckeredPaperItem(new Item.Settings()));
    public static final Item PINK_CIRCULAR_PAPER = registerItem("pink_circular_paper", new PinkCircularPaperItem(new Item.Settings()));
    public static final Item PINK_CROSSED_PAPER = registerItem("pink_crossed_paper", new PinkCrossedPaperItem(new Item.Settings()));
    public static final Item PINK_DIAMOND_PAPER = registerItem("pink_diamond_paper", new PinkDiamondPaperItem(new Item.Settings()));
    public static final Item PINK_GRASS_PAPER = registerItem("pink_grass_paper", new PinkGrassPaperItem(new Item.Settings()));
    public static final Item PINK_INTERLINKED_PAPER = registerItem("pink_interlinked_paper", new PinkInterlinkedPaperItem(new Item.Settings()));
    public static final Item PINK_LAYERED_PAPER = registerItem("pink_layered_paper", new PinkLayeredPaperItem(new Item.Settings()));
    public static final Item PINK_LILY_FLOWER_PAPER = registerItem("pink_lily_flower_paper", new PinkLilyFlowerPaperItem(new Item.Settings()));
    public static final Item PINK_OCULAR_PAPER = registerItem("pink_ocular_paper", new PinkOcularPaperItem(new Item.Settings()));
    public static final Item PINK_OVAL_PAPER = registerItem("pink_oval_paper", new PinkOvalPaperItem(new Item.Settings()));
    public static final Item PINK_PYRIFORM_PAPER = registerItem("pink_pyriform_paper", new PinkPyriformPaperItem(new Item.Settings()));
    public static final Item PINK_SCALES_PAPER = registerItem("pink_scales_paper", new PinkScalesPaperItem(new Item.Settings()));
    public static final Item PINK_TWISTED_PAPER = registerItem("pink_twisted_paper", new PinkTwistedPaperItem(new Item.Settings()));
    public static final Item PINK_TWO_STARRED_PAPER = registerItem("pink_two_starred_paper", new PinkTwoStarredPaperItem(new Item.Settings()));
    public static final Item PINK_ZIPPER_PAPER = registerItem("pink_zipper_paper", new PinkZipperPaperItem(new Item.Settings()));
    public static final Item PURPLE_CHAIN_LINK_PAPER = registerItem("purple_chain_link_paper", new PurpleChainLinkPaperItem(new Item.Settings()));
    public static final Item PURPLE_CHECKERED_PAPER = registerItem("purple_checkered_paper", new PurpleCheckeredPaperItem(new Item.Settings()));
    public static final Item PURPLE_CIRCULAR_PAPER = registerItem("purple_circular_paper", new PurpleCircularPaperItem(new Item.Settings()));
    public static final Item PURPLE_CROSSED_PAPER = registerItem("purple_crossed_paper", new PurpleCrossedPaperItem(new Item.Settings()));
    public static final Item PURPLE_DIAMOND_PAPER = registerItem("purple_diamond_paper", new PurpleDiamondPaperItem(new Item.Settings()));
    public static final Item PURPLE_GRASS_PAPER = registerItem("purple_grass_paper", new PurpleGrassPaperItem(new Item.Settings()));
    public static final Item PURPLE_INTERLINKED_PAPER = registerItem("purple_interlinked_paper", new PurpleInterlinkedPaperItem(new Item.Settings()));
    public static final Item PURPLE_LAYERED_PAPER = registerItem("purple_layered_paper", new PurpleLayeredPaperItem(new Item.Settings()));
    public static final Item PURPLE_LILY_FLOWER_PAPER = registerItem("purple_lily_flower_paper", new PurpleLilyFlowerPaperItem(new Item.Settings()));
    public static final Item PURPLE_OCULAR_PAPER = registerItem("purple_ocular_paper", new PurpleOcularPaperItem(new Item.Settings()));
    public static final Item PURPLE_OVAL_PAPER = registerItem("purple_oval_paper", new PurpleOvalPaperItem(new Item.Settings()));
    public static final Item PURPLE_PYRIFORM_PAPER = registerItem("purple_pyriform_paper", new PurplePyriformPaperItem(new Item.Settings()));
    public static final Item PURPLE_SCALES_PAPER = registerItem("purple_scales_paper", new PurpleScalesPaperItem(new Item.Settings()));
    public static final Item PURPLE_TWISTED_PAPER = registerItem("purple_twisted_paper", new PurpleTwistedPaperItem(new Item.Settings()));
    public static final Item PURPLE_TWO_STARRED_PAPER = registerItem("purple_two_starred_paper", new PurpleTwoStarredPaperItem(new Item.Settings()));
    public static final Item PURPLE_ZIPPER_PAPER = registerItem("purple_zipper_paper", new PurpleZipperPaperItem(new Item.Settings()));
    public static final Item RED_CHAIN_LINK_PAPER = registerItem("red_chain_link_paper", new RedChainLinkPaperItem(new Item.Settings()));
    public static final Item RED_CHECKERED_PAPER = registerItem("red_checkered_paper", new RedCheckeredPaperItem(new Item.Settings()));
    public static final Item RED_CIRCULAR_PAPER = registerItem("red_circular_paper", new RedCircularPaperItem(new Item.Settings()));
    public static final Item RED_CROSSED_PAPER = registerItem("red_crossed_paper", new RedCrossedPaperItem(new Item.Settings()));
    public static final Item RED_DIAMOND_PAPER = registerItem("red_diamond_paper", new RedDiamondPaperItem(new Item.Settings()));
    public static final Item RED_GRASS_PAPER = registerItem("red_grass_paper", new RedGrassPaperItem(new Item.Settings()));
    public static final Item RED_INTERLINKED_PAPER = registerItem("red_interlinked_paper", new RedInterlinkedPaperItem(new Item.Settings()));
    public static final Item RED_LAYERED_PAPER = registerItem("red_layered_paper", new RedLayeredPaperItem(new Item.Settings()));
    public static final Item RED_LILY_FLOWER_PAPER = registerItem("red_lily_flower_paper", new RedLilyFlowerPaperItem(new Item.Settings()));
    public static final Item RED_OCULAR_PAPER = registerItem("red_ocular_paper", new RedOcularPaperItem(new Item.Settings()));
    public static final Item RED_OVAL_PAPER = registerItem("red_oval_paper", new RedOvalPaperItem(new Item.Settings()));
    public static final Item RED_PYRIFORM_PAPER = registerItem("red_pyriform_paper", new RedPyriformPaperItem(new Item.Settings()));
    public static final Item RED_SCALES_PAPER = registerItem("red_scales_paper", new RedScalesPaperItem(new Item.Settings()));
    public static final Item RED_TWISTED_PAPER = registerItem("red_twisted_paper", new RedTwistedPaperItem(new Item.Settings()));
    public static final Item RED_TWO_STARRED_PAPER = registerItem("red_two_starred_paper", new RedTwoStarredPaperItem(new Item.Settings()));
    public static final Item RED_ZIPPER_PAPER = registerItem("red_zipper_paper", new RedZipperPaperItem(new Item.Settings()));
    public static final Item WHITE_CHAIN_LINK_PAPER = registerItem("white_chain_link_paper", new WhiteChainLinkPaperItem(new Item.Settings()));
    public static final Item WHITE_CHECKERED_PAPER = registerItem("white_checkered_paper", new WhiteCheckeredPaperItem(new Item.Settings()));
    public static final Item WHITE_CIRCULAR_PAPER = registerItem("white_circular_paper", new WhiteCircularPaperItem(new Item.Settings()));
    public static final Item WHITE_CROSSED_PAPER = registerItem("white_crossed_paper", new WhiteCrossedPaperItem(new Item.Settings()));
    public static final Item WHITE_DIAMOND_PAPER = registerItem("white_diamond_paper", new WhiteDiamondPaperItem(new Item.Settings()));
    public static final Item WHITE_GRASS_PAPER = registerItem("white_grass_paper", new WhiteGrassPaperItem(new Item.Settings()));
    public static final Item WHITE_INTERLINKED_PAPER = registerItem("white_interlinked_paper", new WhiteInterlinkedPaperItem(new Item.Settings()));
    public static final Item WHITE_LAYERED_PAPER = registerItem("white_layered_paper", new WhiteLayeredPaperItem(new Item.Settings()));
    public static final Item WHITE_LILY_FLOWER_PAPER = registerItem("white_lily_flower_paper", new WhiteLilyFlowerPaperItem(new Item.Settings()));
    public static final Item WHITE_OCULAR_PAPER = registerItem("white_ocular_paper", new WhiteOcularPaperItem(new Item.Settings()));
    public static final Item WHITE_OVAL_PAPER = registerItem("white_oval_paper", new WhiteOvalPaperItem(new Item.Settings()));
    public static final Item WHITE_PYRIFORM_PAPER = registerItem("white_pyriform_paper", new WhitePyriformPaperItem(new Item.Settings()));
    public static final Item WHITE_SCALES_PAPER = registerItem("white_scales_paper", new WhiteScalesPaperItem(new Item.Settings()));
    public static final Item WHITE_TWISTED_PAPER = registerItem("white_twisted_paper", new WhiteTwistedPaperItem(new Item.Settings()));
    public static final Item WHITE_TWO_STARRED_PAPER = registerItem("white_two_starred_paper", new WhiteTwoStarredPaperItem(new Item.Settings()));
    public static final Item WHITE_ZIPPER_PAPER = registerItem("white_zipper_paper", new WhiteZipperPaperItem(new Item.Settings()));
    public static final Item YELLOW_CHAIN_LINK_PAPER = registerItem("yellow_chain_link_paper", new YellowChainLinkPaperItem(new Item.Settings()));
    public static final Item YELLOW_CHECKERED_PAPER = registerItem("yellow_checkered_paper", new YellowCheckeredPaperItem(new Item.Settings()));
    public static final Item YELLOW_CIRCULAR_PAPER = registerItem("yellow_circular_paper", new YellowCircularPaperItem(new Item.Settings()));
    public static final Item YELLOW_CROSSED_PAPER = registerItem("yellow_crossed_paper", new YellowCrossedPaperItem(new Item.Settings()));
    public static final Item YELLOW_DIAMOND_PAPER = registerItem("yellow_diamond_paper", new YellowDiamondPaperItem(new Item.Settings()));
    public static final Item YELLOW_GRASS_PAPER = registerItem("yellow_grass_paper", new YellowGrassPaperItem(new Item.Settings()));
    public static final Item YELLOW_INTERLINKED_PAPER = registerItem("yellow_interlinked_paper", new YellowInterlinkedPaperItem(new Item.Settings()));
    public static final Item YELLOW_LAYERED_PAPER = registerItem("yellow_layered_paper", new YellowLayeredPaperItem(new Item.Settings()));
    public static final Item YELLOW_LILY_FLOWER_PAPER = registerItem("yellow_lily_flower_paper", new YellowLilyFlowerPaperItem(new Item.Settings()));
    public static final Item YELLOW_OCULAR_PAPER = registerItem("yellow_ocular_paper", new YellowOcularPaperItem(new Item.Settings()));
    public static final Item YELLOW_OVAL_PAPER = registerItem("yellow_oval_paper", new YellowOvalPaperItem(new Item.Settings()));
    public static final Item YELLOW_PYRIFORM_PAPER = registerItem("yellow_pyriform_paper", new YellowPyriformPaperItem(new Item.Settings()));
    public static final Item YELLOW_SCALES_PAPER = registerItem("yellow_scales_paper", new YellowScalesPaperItem(new Item.Settings()));
    public static final Item YELLOW_TWISTED_PAPER = registerItem("yellow_twisted_paper", new YellowTwistedPaperItem(new Item.Settings()));
    public static final Item YELLOW_TWO_STARRED_PAPER = registerItem("yellow_two_starred_paper", new YellowTwoStarredPaperItem(new Item.Settings()));
    public static final Item YELLOW_ZIPPER_PAPER = registerItem("yellow_zipper_paper", new YellowZipperPaperItem(new Item.Settings()));
    public static final Item WHITE_FLOWER_CHARGE_PAPER = registerItem("white_flower_charge_paper", new WhiteFlowerChargePaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_FLOWER_CHARGE_PAPER = registerItem("light_gray_flower_charge_paper", new LightGrayFlowerChargePaperItem(new Item.Settings()));
    public static final Item GRAY_FLOWER_CHARGE_PAPER = registerItem("gray_flower_charge_paper", new GrayFlowerChargePaperItem(new Item.Settings()));
    public static final Item BLACK_FLOWER_CHARGE_PAPER = registerItem("black_flower_charge_paper", new BlackFlowerChargePaperItem(new Item.Settings()));
    public static final Item BROWN_FLOWER_CHARGE_PAPER = registerItem("brown_flower_charge_paper", new BrownFlowerChargePaperItem(new Item.Settings()));
    public static final Item RED_FLOWER_CHARGE_PAPER = registerItem("red_flower_charge_paper", new RedFlowerChargePaperItem(new Item.Settings()));
    public static final Item ORANGE_FLOWER_CHARGE_PAPER = registerItem("orange_flower_charge_paper", new OrangeFlowerChargePaperItem(new Item.Settings()));
    public static final Item YELLOW_FLOWER_CHARGE_PAPER = registerItem("yellow_flower_charge_paper", new YellowFlowerChargePaperItem(new Item.Settings()));
    public static final Item LIME_FLOWER_CHARGE_PAPER = registerItem("lime_flower_charge_paper", new LimeFlowerChargePaperItem(new Item.Settings()));
    public static final Item GREEN_FLOWER_CHARGE_PAPER = registerItem("green_flower_charge_paper", new GreenFlowerChargePaperItem(new Item.Settings()));
    public static final Item CYAN_FLOWER_CHARGE_PAPER = registerItem("cyan_flower_charge_paper", new CyanFlowerChargePaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_FLOWER_CHARGE_PAPER = registerItem("light_blue_flower_charge_paper", new LightBlueFlowerChargePaperItem(new Item.Settings()));
    public static final Item BLUE_FLOWER_CHARGE_PAPER = registerItem("blue_flower_charge_paper", new BlueFlowerChargePaperItem(new Item.Settings()));
    public static final Item PURPLE_FLOWER_CHARGE_PAPER = registerItem("purple_flower_charge_paper", new PurpleFlowerChargePaperItem(new Item.Settings()));
    public static final Item MAGENTA_FLOWER_CHARGE_PAPER = registerItem("magenta_flower_charge_paper", new MagentaFlowerChargePaperItem(new Item.Settings()));
    public static final Item PINK_FLOWER_CHARGE_PAPER = registerItem("pink_flower_charge_paper", new PinkFlowerChargePaperItem(new Item.Settings()));
    public static final Item WHITE_CREEPER_CHARGE_PAPER = registerItem("white_creeper_charge_paper", new WhiteCreeperChargePaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_CREEPER_CHARGE_PAPER = registerItem("light_gray_creeper_charge_paper", new LightGrayCreeperChargePaperItem(new Item.Settings()));
    public static final Item GRAY_CREEPER_CHARGE_PAPER = registerItem("gray_creeper_charge_paper", new GrayCreeperChargePaperItem(new Item.Settings()));
    public static final Item BLACK_CREEPER_CHARGE_PAPER = registerItem("black_creeper_charge_paper", new BlackCreeperChargePaperItem(new Item.Settings()));
    public static final Item BROWN_CREEPER_CHARGE_PAPER = registerItem("brown_creeper_charge_paper", new BrownCreeperChargePaperItem(new Item.Settings()));
    public static final Item RED_CREEPER_CHARGE_PAPER = registerItem("red_creeper_charge_paper", new RedCreeperChargePaperItem(new Item.Settings()));
    public static final Item ORANGE_CREEPER_CHARGE_PAPER = registerItem("orange_creeper_charge_paper", new OrangeCreeperChargePaperItem(new Item.Settings()));
    public static final Item YELLOW_CREEPER_CHARGE_PAPER = registerItem("yellow_creeper_charge_paper", new YellowCreeperChargePaperItem(new Item.Settings()));
    public static final Item LIME_CREEPER_CHARGE_PAPER = registerItem("lime_creeper_charge_paper", new LimeCreeperChargePaperItem(new Item.Settings()));
    public static final Item GREEN_CREEPER_CHARGE_PAPER = registerItem("green_creeper_charge_paper", new GreenCreeperChargePaperItem(new Item.Settings()));
    public static final Item CYAN_CREEPER_CHARGE_PAPER = registerItem("cyan_creeper_charge_paper", new CyanCreeperChargePaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_CREEPER_CHARGE_PAPER = registerItem("light_blue_creeper_charge_paper", new LightBlueCreeperChargePaperItem(new Item.Settings()));
    public static final Item BLUE_CREEPER_CHARGE_PAPER = registerItem("blue_creeper_charge_paper", new BlueCreeperChargePaperItem(new Item.Settings()));
    public static final Item PURPLE_CREEPER_CHARGE_PAPER = registerItem("purple_creeper_charge_paper", new PurpleCreeperChargePaperItem(new Item.Settings()));
    public static final Item MAGENTA_CREEPER_CHARGE_PAPER = registerItem("magenta_creeper_charge_paper", new MagentaCreeperChargePaperItem(new Item.Settings()));
    public static final Item PINK_CREEPER_CHARGE_PAPER = registerItem("pink_creeper_charge_paper", new PinkCreeperChargePaperItem(new Item.Settings()));
    public static final Item WHITE_SKULL_CHARGE_PAPER = registerItem("white_skull_charge_paper", new WhiteSkullChargePaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_SKULL_CHARGE_PAPER = registerItem("light_gray_skull_charge_paper", new LightGraySkullChargePaperItem(new Item.Settings()));
    public static final Item GRAY_SKULL_CHARGE_PAPER = registerItem("gray_skull_charge_paper", new GraySkullChargePaperItem(new Item.Settings()));
    public static final Item BLACK_SKULL_CHARGE_PAPER = registerItem("black_skull_charge_paper", new BlackSkullChargePaperItem(new Item.Settings()));
    public static final Item BROWN_SKULL_CHARGE_PAPER = registerItem("brown_skull_charge_paper", new BrownSkullChargePaperItem(new Item.Settings()));
    public static final Item RED_SKULL_CHARGE_PAPER = registerItem("red_skull_charge_paper", new RedSkullChargePaperItem(new Item.Settings()));
    public static final Item ORANGE_SKULL_CHARGE_PAPER = registerItem("orange_skull_charge_paper", new OrangeSkullChargePaperItem(new Item.Settings()));
    public static final Item YELLOW_SKULL_CHARGE_PAPER = registerItem("yellow_skull_charge_paper", new YellowSkullChargePaperItem(new Item.Settings()));
    public static final Item LIME_SKULL_CHARGE_PAPER = registerItem("lime_skull_charge_paper", new LimeSkullChargePaperItem(new Item.Settings()));
    public static final Item GREEN_SKULL_CHARGE_PAPER = registerItem("green_skull_charge_paper", new GreenSkullChargePaperItem(new Item.Settings()));
    public static final Item CYAN_SKULL_CHARGE_PAPER = registerItem("cyan_skull_charge_paper", new CyanSkullChargePaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_SKULL_CHARGE_PAPER = registerItem("light_blue_skull_charge_paper", new LightBlueSkullChargePaperItem(new Item.Settings()));
    public static final Item BLUE_SKULL_CHARGE_PAPER = registerItem("blue_skull_charge_paper", new BlueSkullChargePaperItem(new Item.Settings()));
    public static final Item PURPLE_SKULL_CHARGE_PAPER = registerItem("purple_skull_charge_paper", new PurpleSkullChargePaperItem(new Item.Settings()));
    public static final Item MAGENTA_SKULL_CHARGE_PAPER = registerItem("magenta_skull_charge_paper", new MagentaSkullChargePaperItem(new Item.Settings()));
    public static final Item PINK_SKULL_CHARGE_PAPER = registerItem("pink_skull_charge_paper", new PinkSkullChargePaperItem(new Item.Settings()));
    public static final Item WHITE_SNOUT_PAPER = registerItem("white_snout_paper", new WhiteSnoutPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_SNOUT_PAPER = registerItem("light_gray_snout_paper", new LightGraySnoutPaperItem(new Item.Settings()));
    public static final Item GRAY_SNOUT_PAPER = registerItem("gray_snout_paper", new GraySnoutPaperItem(new Item.Settings()));
    public static final Item BLACK_SNOUT_PAPER = registerItem("black_snout_paper", new WhiteSnoutPaperItem(new Item.Settings()));
    public static final Item BROWN_SNOUT_PAPER = registerItem("brown_snout_paper", new WhiteSnoutPaperItem(new Item.Settings()));
    public static final Item RED_SNOUT_PAPER = registerItem("red_snout_paper", new RedSnoutPaperItem(new Item.Settings()));
    public static final Item ORANGE_SNOUT_PAPER = registerItem("orange_snout_paper", new OrangeSnoutPaperItem(new Item.Settings()));
    public static final Item YELLOW_SNOUT_PAPER = registerItem("yellow_snout_paper", new YellowSnoutPaperItem(new Item.Settings()));
    public static final Item LIME_SNOUT_PAPER = registerItem("lime_snout_paper", new LimeSnoutPaperItem(new Item.Settings()));
    public static final Item GREEN_SNOUT_PAPER = registerItem("green_snout_paper", new WhiteSnoutPaperItem(new Item.Settings()));
    public static final Item CYAN_SNOUT_PAPER = registerItem("cyan_snout_paper", new CyanSnoutPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_SNOUT_PAPER = registerItem("light_blue_snout_paper", new LightBlueSnoutPaperItem(new Item.Settings()));
    public static final Item BLUE_SNOUT_PAPER = registerItem("blue_snout_paper", new BlueSnoutPaperItem(new Item.Settings()));
    public static final Item PURPLE_SNOUT_PAPER = registerItem("purple_snout_paper", new PurpleSnoutPaperItem(new Item.Settings()));
    public static final Item MAGENTA_SNOUT_PAPER = registerItem("magenta_snout_paper", new MagentaSnoutPaperItem(new Item.Settings()));
    public static final Item PINK_SNOUT_PAPER = registerItem("pink_snout_paper", new PinkSnoutPaperItem(new Item.Settings()));
    public static final Item WHITE_THING_PAPER = registerItem("white_thing_paper", new WhiteThingPaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_THING_PAPER = registerItem("light_gray_thing_paper", new LightGrayThingPaperItem(new Item.Settings()));
    public static final Item GRAY_THING_PAPER = registerItem("gray_thing_paper", new GrayThingPaperItem(new Item.Settings()));
    public static final Item BLACK_THING_PAPER = registerItem("black_thing_paper", new BlackThingPaperItem(new Item.Settings()));
    public static final Item BROWN_THING_PAPER = registerItem("brown_thing_paper", new BrownThingPaperItem(new Item.Settings()));
    public static final Item RED_THING_PAPER = registerItem("red_thing_paper", new RedThingPaperItem(new Item.Settings()));
    public static final Item ORANGE_THING_PAPER = registerItem("orange_thing_paper", new OrangeThingPaperItem(new Item.Settings()));
    public static final Item YELLOW_THING_PAPER = registerItem("yellow_thing_paper", new YellowThingPaperItem(new Item.Settings()));
    public static final Item LIME_THING_PAPER = registerItem("lime_thing_paper", new LimeThingPaperItem(new Item.Settings()));
    public static final Item GREEN_THING_PAPER = registerItem("green_thing_paper", new GreenThingPaperItem(new Item.Settings()));
    public static final Item CYAN_THING_PAPER = registerItem("cyan_thing_paper", new CyanThingPaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_THING_PAPER = registerItem("light_blue_thing_paper", new LightBlueThingPaperItem(new Item.Settings()));
    public static final Item BLUE_THING_PAPER = registerItem("blue_thing_paper", new BlueThingPaperItem(new Item.Settings()));
    public static final Item PURPLE_THING_PAPER = registerItem("purple_thing_paper", new PurpleThingPaperItem(new Item.Settings()));
    public static final Item MAGENTA_THING_PAPER = registerItem("magenta_thing_paper", new MagentaThingPaperItem(new Item.Settings()));
    public static final Item PINK_THING_PAPER = registerItem("pink_thing_paper", new PinkThingPaperItem(new Item.Settings()));
    public static final Item WHITE_GLOBE_PAPER = registerItem("white_globe_paper", new WhiteGlobePaperItem(new Item.Settings()));
    public static final Item LIGHT_GRAY_GLOBE_PAPER = registerItem("light_gray_globe_paper", new LightGrayGlobePaperItem(new Item.Settings()));
    public static final Item GRAY_GLOBE_PAPER = registerItem("gray_globe_paper", new GrayGlobePaperItem(new Item.Settings()));
    public static final Item BLACK_GLOBE_PAPER = registerItem("black_globe_paper", new BlackGlobePaperItem(new Item.Settings()));
    public static final Item BROWN_GLOBE_PAPER = registerItem("brown_globe_paper", new BrownGlobePaperItem(new Item.Settings()));
    public static final Item RED_GLOBE_PAPER = registerItem("red_globe_paper", new RedGlobePaperItem(new Item.Settings()));
    public static final Item ORANGE_GLOBE_PAPER = registerItem("orange_globe_paper", new OrangeGlobePaperItem(new Item.Settings()));
    public static final Item YELLOW_GLOBE_PAPER = registerItem("yellow_globe_paper", new YellowGlobePaperItem(new Item.Settings()));
    public static final Item LIME_GLOBE_PAPER = registerItem("lime_globe_paper", new LimeGlobePaperItem(new Item.Settings()));
    public static final Item GREEN_GLOBE_PAPER = registerItem("green_globe_paper", new GreenGlobePaperItem(new Item.Settings()));
    public static final Item CYAN_GLOBE_PAPER = registerItem("cyan_globe_paper", new CyanGlobePaperItem(new Item.Settings()));
    public static final Item LIGHT_BLUE_GLOBE_PAPER = registerItem("light_blue_globe_paper", new LightBlueGlobePaperItem(new Item.Settings()));
    public static final Item BLUE_GLOBE_PAPER = registerItem("blue_globe_paper", new BlueGlobePaperItem(new Item.Settings()));
    public static final Item PURPLE_GLOBE_PAPER = registerItem("purple_globe_paper", new PurpleGlobePaperItem(new Item.Settings()));
    public static final Item MAGENTA_GLOBE_PAPER = registerItem("magenta_globe_paper", new MagentaGlobePaperItem(new Item.Settings()));
    public static final Item PINK_GLOBE_PAPER = registerItem("pink_globe_paper", new PinkGlobePaperItem(new Item.Settings()));

    public static final Item IRON_RAPIER = registerItem("iron_rapier",
            new SwordItem(ModToolMaterial.IRON, 2, 2f, new FabricItemSettings()));
    public static final Item GOLD_RAPIER = registerItem("gold_rapier",
            new SwordItem(ModToolMaterial.GOLD, 2, 2f, new FabricItemSettings()));
    public static final Item COPPER_RAPIER = registerItem("copper_rapier",
            new SwordItem(ModToolMaterial.COPPER, 2, 2f, new FabricItemSettings()));
    public static final Item STEEL_RAPIER = registerItem("steel_rapier",
            new SwordItem(ModToolMaterial.STEEL, 2, 2f, new FabricItemSettings()));
    public static final Item DIAMOND_RAPIER = registerItem("diamond_rapier",
            new SwordItem(ModToolMaterial.DIAMOND, 2, 2f, new FabricItemSettings()));
    public static final Item NETHERITE_RAPIER = registerItem("netherite_rapier",
            new SwordItem(ModToolMaterial.NETHERITE, 2, 2f, new FabricItemSettings()));


    public static final Item HUNTERS_HAT = registerItem("hunters_hat",
            new HuntersHatItem(ModArmorMaterials.HUNTERS_HAT, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item NEWSPAPER_BOY_HAT = registerItem("newspaper_boy_hat",
            new NewsPaperBoyHatItem(ModArmorMaterials.NEWSPAPER_BOY_HAT, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item TOP_HAT = registerItem("top_hat",
            new TopHatItem(ModArmorMaterials.TOP_HAT, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item FLOWER_CROWN = registerItem("flower_crown",
            new ArmorItem(ModArmorMaterials.FLOWER_CROWN, ArmorItem.Type.HELMET, new FabricItemSettings()));

    private static void addItemsToIngredientItemGroup(FabricItemGroupEntries entries) {
        entries.add(STEEL_INGOT);
        entries.add(VICTORIAN_BANNER_PATTERN);
        entries.add(CHAIN_LINKS_BANNER_PATTERN);
        entries.add(STEEL_NUGGET);
        entries.add(RAW_PORCELAIN);
        entries.add(PORCELAIN_BRICK);
        entries.add(HUNTERS_HAT);
        entries.add(NEWSPAPER_BOY_HAT);
        entries.add(TOP_HAT);
        entries.add(FLOWER_CROWN);

    }

    private static Item registerItem(String name, Item item) {
        return Registry.register(Registries.ITEM, new Identifier(FlamesVictorianMadness.MOD_ID, name), item);
    }

    public static void registerModItems() {
        FlamesVictorianMadness.LOGGER.info("Registering Mod Items for " + FlamesVictorianMadness.MOD_ID);

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.INGREDIENTS).register(ModItems::addItemsToIngredientItemGroup);
    }
}
