package net.flamesparks4143.datagen;

import com.eliotlash.mclib.math.functions.classic.Mod;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.flamesparks4143.block.ModBlocks;
import net.flamesparks4143.item.ModItems;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.*;
import net.minecraft.item.ArmorItem;
import net.minecraft.util.Identifier;


public class ModModelProvider extends FabricModelProvider {
    public ModModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override

    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        BlockStateModelGenerator.BlockTexturePool steelPool =  blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.STEEL_BLOCK);
        BlockStateModelGenerator.BlockTexturePool brickPool =  blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PORCELAIN_BRICKS);
        BlockStateModelGenerator.BlockTexturePool porcelainPool =  blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PORCELAIN_BLOCK);

        steelPool.stairs(ModBlocks.STEEL_STAIRS);
        steelPool.slab(ModBlocks.STEEL_SLAB);
        steelPool.pressurePlate(ModBlocks.STEEL_PRESSURE_PLATE);
        blockStateModelGenerator.registerDoor(ModBlocks.STEEL_DOOR);
        blockStateModelGenerator.registerDoor(ModBlocks.STEEL_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.STEEL_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.STEEL_DOOR_SUN);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.STEEL_TRAPDOOR);

        brickPool.stairs(ModBlocks.PORCELAIN_BRICKS_STAIRS);
        brickPool.slab(ModBlocks.PORCELAIN_BRICKS_SLAB);
        brickPool.wall(ModBlocks.PORCELAIN_BRICKS_WALL);
        porcelainPool.stairs(ModBlocks.PORCELAIN_STAIRS);
        porcelainPool.slab(ModBlocks.PORCELAIN_SLAB);
        porcelainPool.wall(ModBlocks.PORCELAIN_WALL);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRACKED_PORCELAIN_BRICKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.CHISELED_PORCELAIN, TexturedModel.CUBE_COLUMN);

        blockStateModelGenerator.registerGlassPane(ModBlocks.BLACK_CATHEDRAL_STAINED_GLASS, ModBlocks.BLACK_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLACK_EMERALD_STAINED_GLASS, ModBlocks.BLACK_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLACK_DIAMOND_STAINED_GLASS, ModBlocks.BLACK_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLACK_SQUARE_STAINED_GLASS, ModBlocks.BLACK_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLUE_CATHEDRAL_STAINED_GLASS, ModBlocks.BLUE_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLUE_EMERALD_STAINED_GLASS, ModBlocks.BLUE_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLUE_DIAMOND_STAINED_GLASS, ModBlocks.BLUE_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BLUE_SQUARE_STAINED_GLASS, ModBlocks.BLUE_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BROWN_CATHEDRAL_STAINED_GLASS, ModBlocks.BROWN_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BROWN_EMERALD_STAINED_GLASS, ModBlocks.BROWN_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BROWN_DIAMOND_STAINED_GLASS, ModBlocks.BROWN_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.BROWN_SQUARE_STAINED_GLASS, ModBlocks.BROWN_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_GRAY_CATHEDRAL_STAINED_GLASS, ModBlocks.LIGHT_GRAY_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_GRAY_EMERALD_STAINED_GLASS, ModBlocks.LIGHT_GRAY_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_GRAY_DIAMOND_STAINED_GLASS, ModBlocks.LIGHT_GRAY_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_GRAY_SQUARE_STAINED_GLASS, ModBlocks.LIGHT_GRAY_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GRAY_CATHEDRAL_STAINED_GLASS, ModBlocks.GRAY_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GRAY_EMERALD_STAINED_GLASS, ModBlocks.GRAY_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GRAY_DIAMOND_STAINED_GLASS, ModBlocks.GRAY_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GRAY_SQUARE_STAINED_GLASS, ModBlocks.GRAY_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.WHITE_CATHEDRAL_STAINED_GLASS, ModBlocks.WHITE_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.WHITE_EMERALD_STAINED_GLASS, ModBlocks.WHITE_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.WHITE_DIAMOND_STAINED_GLASS, ModBlocks.WHITE_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.WHITE_SQUARE_STAINED_GLASS, ModBlocks.WHITE_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.RED_CATHEDRAL_STAINED_GLASS, ModBlocks.RED_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.RED_EMERALD_STAINED_GLASS, ModBlocks.RED_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.RED_DIAMOND_STAINED_GLASS, ModBlocks.RED_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.RED_SQUARE_STAINED_GLASS, ModBlocks.RED_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.ORANGE_CATHEDRAL_STAINED_GLASS, ModBlocks.ORANGE_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.ORANGE_EMERALD_STAINED_GLASS, ModBlocks.ORANGE_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.ORANGE_DIAMOND_STAINED_GLASS, ModBlocks.ORANGE_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.ORANGE_SQUARE_STAINED_GLASS, ModBlocks.ORANGE_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.YELLOW_CATHEDRAL_STAINED_GLASS, ModBlocks.YELLOW_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.YELLOW_EMERALD_STAINED_GLASS, ModBlocks.YELLOW_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.YELLOW_DIAMOND_STAINED_GLASS, ModBlocks.YELLOW_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.YELLOW_SQUARE_STAINED_GLASS, ModBlocks.YELLOW_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIME_CATHEDRAL_STAINED_GLASS, ModBlocks.LIME_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIME_EMERALD_STAINED_GLASS, ModBlocks.LIME_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIME_DIAMOND_STAINED_GLASS, ModBlocks.LIME_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIME_SQUARE_STAINED_GLASS, ModBlocks.LIME_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GREEN_CATHEDRAL_STAINED_GLASS, ModBlocks.GREEN_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GREEN_EMERALD_STAINED_GLASS, ModBlocks.GREEN_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GREEN_DIAMOND_STAINED_GLASS, ModBlocks.GREEN_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.GREEN_SQUARE_STAINED_GLASS, ModBlocks.GREEN_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.CYAN_CATHEDRAL_STAINED_GLASS, ModBlocks.CYAN_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.CYAN_EMERALD_STAINED_GLASS, ModBlocks.CYAN_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.CYAN_DIAMOND_STAINED_GLASS, ModBlocks.CYAN_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.CYAN_SQUARE_STAINED_GLASS, ModBlocks.CYAN_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_BLUE_CATHEDRAL_STAINED_GLASS, ModBlocks.LIGHT_BLUE_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_BLUE_EMERALD_STAINED_GLASS, ModBlocks.LIGHT_BLUE_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_BLUE_DIAMOND_STAINED_GLASS, ModBlocks.LIGHT_BLUE_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.LIGHT_BLUE_SQUARE_STAINED_GLASS, ModBlocks.LIGHT_BLUE_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PURPLE_CATHEDRAL_STAINED_GLASS, ModBlocks.PURPLE_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PURPLE_EMERALD_STAINED_GLASS, ModBlocks.PURPLE_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PURPLE_DIAMOND_STAINED_GLASS, ModBlocks.PURPLE_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PURPLE_SQUARE_STAINED_GLASS, ModBlocks.PURPLE_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.MAGENTA_CATHEDRAL_STAINED_GLASS, ModBlocks.MAGENTA_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.MAGENTA_EMERALD_STAINED_GLASS, ModBlocks.MAGENTA_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.MAGENTA_DIAMOND_STAINED_GLASS, ModBlocks.MAGENTA_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.MAGENTA_SQUARE_STAINED_GLASS, ModBlocks.MAGENTA_SQUARE_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PINK_CATHEDRAL_STAINED_GLASS, ModBlocks.PINK_CATHEDRAL_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PINK_EMERALD_STAINED_GLASS, ModBlocks.PINK_EMERALD_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PINK_DIAMOND_STAINED_GLASS, ModBlocks.PINK_DIAMOND_STAINED_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.PINK_SQUARE_STAINED_GLASS, ModBlocks.PINK_SQUARE_STAINED_PANE);

        blockStateModelGenerator.registerGlassPane(ModBlocks.FLOWER_GLASS, ModBlocks.FLOWER_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.MOON_GLASS, ModBlocks.MOON_PANE);
        blockStateModelGenerator.registerGlassPane(ModBlocks.SUN_GLASS, ModBlocks.SUN_PANE);

        blockStateModelGenerator.registerDoor(ModBlocks.OAK_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.OAK_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.OAK_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.BIRCH_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.BIRCH_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.BIRCH_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.JUNGLE_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.JUNGLE_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.JUNGLE_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.ACACIA_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.ACACIA_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.ACACIA_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.DARK_OAK_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.DARK_OAK_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.DARK_OAK_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.MANGROVE_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.MANGROVE_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.MANGROVE_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.CHERRY_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.CHERRY_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.CHERRY_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.BAMBOO_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.BAMBOO_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.BAMBOO_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.CRIMSON_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.CRIMSON_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.CRIMSON_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.WARPED_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.WARPED_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.WARPED_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.IRON_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.IRON_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.IRON_DOOR_SUN);
        blockStateModelGenerator.registerDoor(ModBlocks.SPRUCE_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.SPRUCE_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.SPRUCE_DOOR_SUN);

        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.WHITE_PATTERN_WOOL, ModBlocks.WHITE_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.LIGHT_GRAY_PATTERN_WOOL, ModBlocks.LIGHT_GRAY_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.GRAY_PATTERN_WOOL, ModBlocks.GRAY_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.BLACK_PATTERN_WOOL, ModBlocks.BLACK_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.RED_PATTERN_WOOL, ModBlocks.RED_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.ORANGE_PATTERN_WOOL, ModBlocks.ORANGE_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.YELLOW_PATTERN_WOOL, ModBlocks.YELLOW_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.LIME_PATTERN_WOOL, ModBlocks.LIME_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.GREEN_PATTERN_WOOL, ModBlocks.GREEN_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.CYAN_PATTERN_WOOL, ModBlocks.CYAN_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.LIGHT_BLUE_PATTERN_WOOL, ModBlocks.LIGHT_BLUE_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.BLUE_PATTERN_WOOL, ModBlocks.BLUE_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.PURPLE_PATTERN_WOOL, ModBlocks.PURPLE_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.BROWN_PATTERN_WOOL, ModBlocks.BROWN_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.MAGENTA_PATTERN_WOOL, ModBlocks.MAGENTA_PATTERN_CARPET);
        blockStateModelGenerator.registerWoolAndCarpet(ModBlocks.PINK_PATTERN_WOOL, ModBlocks.PINK_PATTERN_CARPET);

        blockStateModelGenerator.registerDoor(ModBlocks.GOLD_DOOR);
        blockStateModelGenerator.registerDoor(ModBlocks.GOLD_DOOR_FLOWER);
        blockStateModelGenerator.registerDoor(ModBlocks.GOLD_DOOR_MOON);
        blockStateModelGenerator.registerDoor(ModBlocks.GOLD_DOOR_SUN);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.GOLD_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.ANDESITE_PILLAR).log(ModBlocks.ANDESITE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.GRANITE_PILLAR).log(ModBlocks.GRANITE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.DIORITE_PILLAR).log(ModBlocks.DIORITE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.DEEPSLATE_PILLAR).log(ModBlocks.DEEPSLATE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.TUFF_PILLAR).log(ModBlocks.TUFF_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.END_STONE_PILLAR).log(ModBlocks.END_STONE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.BLACKSTONE_PILLAR).log(ModBlocks.BLACKSTONE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.GILDED_BLACKSTONE_PILLAR).log(ModBlocks.GILDED_BLACKSTONE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.PORCELAIN_PILLAR).log(ModBlocks.PORCELAIN_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.BASALT_PILLAR).log(ModBlocks.BASALT_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.STONE_PILLAR).log(ModBlocks.STONE_PILLAR);
        blockStateModelGenerator.registerLog(ModBlocks.CALCITE_PILLAR).log(ModBlocks.CALCITE_PILLAR);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_WHITE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_LIGHT_GRAY_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_GRAY_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_BLACK_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_BROWN_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_RED_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_ORANGE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_YELLOW_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_LIME_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_GREEN_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_CYAN_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_LIGHT_BLUE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_BLUE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_PURPLE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_MAGENTA_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_PINK_CONCRETE);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_WHITE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_LIGHT_GRAY_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_GRAY_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_BLACK_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_BROWN_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_RED_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_ORANGE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_YELLOW_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_LIME_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_GREEN_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_CYAN_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_LIGHT_BLUE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_BLUE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_PURPLE_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_MAGENTA_CONCRETE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_PINK_CONCRETE);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_WHITE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_LIGHT_GRAY_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_GRAY_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_BLACK_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_BROWN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_RED_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_ORANGE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_YELLOW_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_LIME_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_GREEN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_CYAN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_LIGHT_BLUE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_BLUE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_PURPLE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_MAGENTA_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHECKERED_PORCELAIN_PINK_TERRACOTTA);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_WHITE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_LIGHT_GRAY_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_GRAY_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_BLACK_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_BROWN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_RED_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_ORANGE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_YELLOW_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_LIME_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_GREEN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_CYAN_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_LIGHT_BLUE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_BLUE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_PURPLE_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_MAGENTA_TERRACOTTA);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.STARRED_PORCELAIN_PINK_TERRACOTTA);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OAK_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OAK_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OAK_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OAK_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OAK_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OAK_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SPRUCE_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SPRUCE_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SPRUCE_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SPRUCE_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SPRUCE_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SPRUCE_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BIRCH_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BIRCH_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BIRCH_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BIRCH_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BIRCH_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BIRCH_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JUNGLE_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JUNGLE_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JUNGLE_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JUNGLE_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JUNGLE_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JUNGLE_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ACACIA_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ACACIA_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ACACIA_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ACACIA_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ACACIA_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ACACIA_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DARK_OAK_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DARK_OAK_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DARK_OAK_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DARK_OAK_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DARK_OAK_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DARK_OAK_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MANGROVE_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MANGROVE_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MANGROVE_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MANGROVE_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MANGROVE_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MANGROVE_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHERRY_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHERRY_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHERRY_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHERRY_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHERRY_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHERRY_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAMBOO_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAMBOO_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAMBOO_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAMBOO_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAMBOO_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BAMBOO_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRIMSON_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRIMSON_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRIMSON_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRIMSON_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRIMSON_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRIMSON_ARCH_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WARPED_CIRCLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WARPED_CORNERS_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WARPED_LINES_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WARPED_SQUARE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WARPED_RECTANGLE_WAINSCOTTING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WARPED_ARCH_WAINSCOTTING);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLANK_WALL);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_LILY_FLOWER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_CHAIN_LINKS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_CHECKERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_CIRCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_CROSSED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_DIAMOND_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_GRASS_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_INTERLINKED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_LAYERED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_OCULAR_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_OVAL_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_PYRIFORM_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_SCALES_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_TWISTED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_TWO_STARRED_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_ZIPPER_WALLPAPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_LILY_FLOWER_WALLPAPER);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_FLOWER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_FLOWER_CHARGE);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_CREEPER_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_CREEPER_CHARGE);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_SKULL_CHARGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_SKULL_CHARGE);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_THING);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_THING);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_GLOBE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_GLOBE);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.WHITE_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_GRAY_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GRAY_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACK_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BROWN_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RED_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORANGE_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.YELLOW_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIME_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GREEN_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CYAN_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIGHT_BLUE_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLUE_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PURPLE_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MAGENTA_SNOUT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PINK_SNOUT);

        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.PURPLE_EYE_DAISY, ModBlocks.POTTED_PURPLE_EYE_DAISY, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.CAMELLIA, ModBlocks.POTTED_CAMELLIA, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.CANTERBURY_BELLS, ModBlocks.POTTED_CANTERBURY_BELLS, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.SHORT_LILAC, ModBlocks.POTTED_SHORT_LILAC, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.SHORT_ROSE_BUSH, ModBlocks.POTTED_SHORT_ROSE_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.SHORT_PONEY_BUSH, ModBlocks.POTTED_SHORT_PONEY_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerDoubleBlock(ModBlocks.BLUE_FOXGLOVES, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerDoubleBlock(ModBlocks.PINK_FOXGLOVES, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerDoubleBlock(ModBlocks.WHITE_FOXGLOVES, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerDoubleBlock(ModBlocks.PURPLE_FOXGLOVES, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerbed(ModBlocks.FORGET_ME_NOTS);
        blockStateModelGenerator.registerFlowerbed(ModBlocks.CROCUSES);


        }


    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.PORCELAIN_BRICK, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAW_PORCELAIN, Models.GENERATED);
        itemModelGenerator.register(ModItems.GLASS_CUTTER, Models.GENERATED);

        itemModelGenerator.register(ModItems.IRON_RAPIER, Models.HANDHELD);
        itemModelGenerator.register(ModItems.DIAMOND_RAPIER, Models.HANDHELD);
        itemModelGenerator.register(ModItems.GOLD_RAPIER, Models.HANDHELD);
        itemModelGenerator.register(ModItems.STEEL_RAPIER, Models.HANDHELD);
        itemModelGenerator.register(ModItems.COPPER_RAPIER, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHERITE_RAPIER, Models.HANDHELD);

        itemModelGenerator.register(ModItems.WHITE_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_FLOWER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_FLOWER_CHARGE_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.WHITE_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_CREEPER_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_CREEPER_CHARGE_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.WHITE_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_SKULL_CHARGE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_SKULL_CHARGE_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.WHITE_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_THING_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_THING_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.WHITE_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_GLOBE_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_GLOBE_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.WHITE_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_SNOUT_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_SNOUT_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.BLUE_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLUE_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLACK_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_GRAY_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAY_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BROWN_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.RED_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YELLOW_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIME_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CYAN_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHT_BLUE_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PURPLE_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGENTA_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINK_LILY_FLOWER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_CHAIN_LINK_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_CHECKERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_CIRCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_CROSSED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_DIAMOND_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_GRASS_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_INTERLINKED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_LAYERED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_OCULAR_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_OVAL_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_PYRIFORM_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_SCALES_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_TWISTED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_TWO_STARRED_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_ZIPPER_PAPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.WHITE_LILY_FLOWER_PAPER, Models.GENERATED);

        itemModelGenerator.register(ModItems.HUNTERS_HAT, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEWSPAPER_BOY_HAT, Models.GENERATED);
        itemModelGenerator.register(ModItems.TOP_HAT, Models.GENERATED);

        itemModelGenerator.registerArmor(((ArmorItem) ModItems.FLOWER_CROWN));

        itemModelGenerator.register(ModItems.STEEL_INGOT, Models.GENERATED);
        itemModelGenerator.register(ModItems.STEEL_NUGGET, Models.GENERATED);

        itemModelGenerator.register(ModItems.CHISEL, Models.GENERATED);
        itemModelGenerator.register(ModItems.VICTORIAN_BANNER_PATTERN, Models.GENERATED);
    }
}
